name: Print APT configuration
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print APT::Get config
        run: |
          apt-config dump | grep APT::Get
