name: Java Setup and Keystore Modification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        id: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print permissions of $JAVA_HOME/lib/security/cacerts
        run: |
          ls -lFa $JAVA_HOME/lib/security/
          
      - name: add p12 to keystore
        run: |
          if [ ! -f my-release-key.p12 ]; then
              keytool -genkeypair -v \
                      -keystore my-release-key.p12 \
                      -storetype PKCS12 \
                      -keyalg RSA \
                      -keysize 2048 \
                      -validity 10000 \
                      -alias my-key \
                      -storepass password \
                      -keypass password \
                      -dname "CN=dummy, OU=dummy, O=dummy, L=dummy, ST=dummy, C=dummy"
          fi
          
          keytool -importkeystore \
            -srckeystore my-release-key.p12 \
            -destkeystore ${{ steps.java.outputs.path }}/lib/security/cacerts \
            -srcalias my-key \
            -srcstorepass password \
            -deststorepass changeit \
            -noprompt

      - uses: ./actions/java-dummy-certificate

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Print permissions of $JAVA_HOME/lib/security/cacerts
        run: |
          ls -lFa $JAVA_HOME/lib/security/cacerts

      - uses: ./actions/java-dummy-certificate

      - name: Print permissions of /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk recursively
        run: |
          ls -laR /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
