name: Java Setup and Keystore Modification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        id: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Print permissions of $JAVA_HOME/lib/security/cacerts
        run: |
          ls -lFa $JAVA_HOME/lib/security/

      - uses: ./actions/java-dummy-certificate

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Print permissions of $JAVA_HOME/lib/security/cacerts
        run: |
          ls -lFa $JAVA_HOME/lib/security/cacerts

      - uses: ./actions/java-dummy-certificate

      - name: Print permissions of /opt/hostedtoolcache recursively
        run: |
          ls -laR /opt/hostedtoolcache
